master_task:
    alias: vm
    freebsd_instance:
      cpu: 4
      memory: 8G
      image: freebsd-14-2-release-amd64-ufs
    vm_setup_script:
      - |
       ./.ci/vm.sh
       kldload fusefs
       mkdir /mnt/vm
       sshfs vm:/ /mnt/vm
