common: &COMMON
    freebsd_instance:
      cpu: 4
      memory: 8G
      image: freebsd-14-2-release-amd64-ufs
master_task:
    alias: pkgs
    <<: *COMMON
    qemu_setup_script:
      - |
       pkg install -y tmux qemu-nox11 vim
       fetch https://github.com/vmactions/dragonflybsd-builder/releases/download/v0.9.8/dragonflybsd-6.4.2.qcow2.zst
       cat dragonflybsd-6.4.2.qcow2.zst | zstd -d > dfbsd.qcow2
       tmux new-session -d

       tmux send-keys -l "qemu-system-x86_64 -drive file="dfbsd.qcow2",if=ide -m 1G -smp 1 -device e1000,netdev=n1,mac=52:54:98:76:54:32 -netdev user,id=n1,net=192.168.122.0/24,dhcpstart=192.168.122.50,hostfwd=tcp::10022-:22 -nographic"

       tmux send-keys Enter

       mkfifo /tmp/panefifo

       tmux pipe-pane -O "cat >> /tmp/panefifo" || echo $?
       echo Waiting for BIOS || echo $?
       fgrep -qm1 'DF/FBSD' /tmp/panefifo   || echo $?
       echo Done waiting for BIOS || echo $?
       tmux pipe-pane -O "cat >> /tmp/panefifo" || echo $?
       # Boot the default BIOS option without waiting. || echo $?
       tmux send-keys Enter || echo $?

       echo Waiting for loader
       fgrep -qm1 'Booting in' /tmp/panefifo 
       tmux pipe-pane -O "cat >> /tmp/panefifo"
       # Boot loader with serial console without waiting
       tmux send-keys -l 9
       tmux send-keys Enter
       tmux send-keys -l set console=comconsole
       tmux send-keys Enter
       tmux send-keys -l boot
       tmux send-keys Enter

       echo Waiting for login
       fgrep -qm1 'login:' /tmp/panefifo   
       tmux pipe-pane -O "cat >> /tmp/panefifo"
       # Wait for getty and login
       tmux send-keys -l "root"
       tmux send-keys Enter
