common: &COMMON
    freebsd_instance:
      cpu: 4
      memory: 8G
      image: freebsd-14-2-release-amd64-ufs
master_task:
    alias: pkgs
    <<: *COMMON
    qemu_setup_script:
      - |
       pkg install -y tmux qemu-nox11 vim
       fetch https://github.com/vmactions/dragonflybsd-builder/releases/download/v0.9.8/dragonflybsd-6.4.2.qcow2.zst
       cat dragonflybsd-6.4.2.qcow2.zst | zstd -d > dfbsd.qcow2
       tmux new-session -d

       tmux send-keys -l "qemu-system-x86_64 -drive file="dfbsd.qcow2",if=ide -display curses -m 1G -smp 1 -device e1000,netdev=n1,mac=52:54:98:76:54:32 -netdev user,id=n1,net=192.168.122.0/24,dhcpstart=192.168.122.50,hostfwd=tcp::10022-:22"
       tmux send-keys Enter
       while ! tmux capture-pane -p | grep -q 'DF/FBSD';do echo Waiting for BIOS; done
       # Boot the default BIOS option without waiting.
       tmux send-keys Enter
       while ! tmux capture-pane -p | grep -q 'Booting in';do echo Waiting for loader; done
       # Boot the default loader option without waiting
       tmux send-keys Enter
       while ! tmux capture-pane -p | grep -q 'login:';do echo Waiting for login; done
       # Wait for getty and login
       tmux send-keys -l root
       tmux send-keys Enter
