common: &COMMON
    freebsd_instance:
      cpu: 4
      memory: 8G
      image: freebsd-14-2-release-amd64-ufs
master_task:
    alias: pkgs
    <<: *COMMON
    qemu_setup_script:
      - |
       pkg install -y tmux qemu-nox11 vim
       fetch https://github.com/vmactions/dragonflybsd-builder/releases/download/v0.9.8/dragonflybsd-6.4.2.qcow2.zst
       cat dragonflybsd-6.4.2.qcow2.zst | zstd -d > dfbsd.qcow2
       tmux new-session -d

       tmux send-keys -l "qemu-system-x86_64 -drive file="dfbsd.qcow2",if=ide -display curses -m 1G -smp 1 -device e1000,netdev=n1,mac=52:54:98:76:54:32 -netdev user,id=n1,net=192.168.122.0/24,dhcpstart=192.168.122.50,hostfwd=tcp::10022-:22"
       tmux send-keys Enter


       tmux pipe-pane -O "cat >> /tmp/panefifo"
       echo Waiting for BIOS
       tail -f /tmp/panefifo | grep -qFm 1 'DF/FBSD'
       # Boot the default BIOS option without waiting.
       tmux send-keys Enter

#       tmux pipe-pane -O "cat >> /tmp/panefifo"
       echo Waiting for loader
       tail -f /tmp/panefifo | grep -qFm 1 'Booting in'
       # Boot the default loader option without waiting
       tmux send-keys Enter

#       tmux pipe-pane -O "cat >> /tmp/panefifo"
       echo Waiting for login
       tail -f /tmp/panefifo | grep -qFm 1 'login:'
       # Wait for getty and login
       tmux send-keys -l "root"
       tmux send-keys Enter
