common: &COMMON
    freebsd_instance:
      cpu: 4
      memory: 8G
      image: freebsd-14-2-release-amd64-ufs
master_task:
    alias: pkgs
    <<: *COMMON
    qemu_setup_script:
      - |
       char-split(){
        tmp="$1"
        while [ -n "$tmp" ]
        do
         rest="${tmp#?}"
         first="${tmp%"$rest"}"
         echo "$first"
         tmp="$rest"
        done
       }
       tmux_sendkeys_slow(){
        IFS=$'\n';
        for i in $(char-split "$1")
        do
         tmux send-keys -l "$i"
         sleep .01
        done
       }

       cc srch.c -o srch

       pkg install -y tmux qemu-nox11 vim
       fetch https://github.com/vmactions/dragonflybsd-builder/releases/download/v0.9.8/dragonflybsd-6.4.2.qcow2.zst
       cat dragonflybsd-6.4.2.qcow2.zst | zstd -d > dfbsd.qcow2
       tmux new-session -d

       tmux send-keys -l "qemu-system-x86_64 -drive file="dfbsd.qcow2",if=ide -m 1G -smp 1 -device e1000,netdev=n1,mac=52:54:98:76:54:32 -netdev user,id=n1,net=192.168.122.0/24,dhcpstart=192.168.122.50,hostfwd=tcp::10022-:22 -nographic"

       tmux send-keys Enter

       tmux pipe-pane -O "cat >> /tmp/dfbsd-log" 

       echo Waiting for BIOS
       (tail -f -n +1  /tmp/dfbsd-log | tr -u '[:special:]' '\n' | tr -u '[:cntrl:]' '\n' & ) |  ./srch 'DF/FBSD' 
       echo Done waiting for BIOS 
       # Boot the default BIOS option without waiting.
       tmux send-keys Enter 

       echo Waiting for loader
       (tail -f -n +1  /tmp/dfbsd-log | tr -u '[:special:]' '\n' | tr -u '[:cntrl:]' '\n' & ) |  ./srch 'Booting in'
       # Boot loader with serial console without waiting
       tmux send-keys -l "                            "

       (tail -f -n +1  /tmp/dfbsd-log | tr -u '[:special:]' '\n' | tr -u '[:cntrl:]' '\n' & ) |  ./srch 'Countdown'

       tmux send-keys -l "9"
       tmux send-keys Enter
       tmux send-keys Enter
       tmux send-keys Enter
       tmux send-keys Enter

       (tail -f -n +1  /tmp/dfbsd-log | tr -u '[:special:]' '\n' | tr -u '[:cntrl:]' '\n' & ) |  ./srch 'OK'

       tmux_sendkeys_slow -l 'set console=comconsole'
       tmux send-keys Enter
       tmux_sendkeys_slow -l 'boot'
       tmux send-keys Enter

       echo Waiting for login
       (tail -f -n +1  /tmp/dfbsd-log | tr -u '[:special:]' '\n' | tr -u '[:cntrl:]' '\n' & ) |  ./srch 'login:'
       # Wait for getty and login
       tmux_sendkeys_slow -l 'root'
       tmux send-keys Enter
