master_task:
    alias: vm
    compute_engine_instance:
      image_project: cirrus-images
      image: family/docker-kvm
      platform: linux
      cpu: 4
      memory: 16G
      nested_virtualization: true
    vm_setup_script:
      - |
       ./.ci/vm.sh
